- path: 
  - /stations
  controller: Controllers\StationsController::insert

- path: 
  - /stations/(\d+)
  controller: Controllers\StationsController::address

- path: 
  - /search
  controller: Controllers\StationsController::search

# - path: 
#   - /todo/delete/(\d+)
#   controller: Controllers\TodoController::delete

# - path: 
#   - /todo/add
#   controller: Controllers\TodoController::add

- path:
  - 
  controller: Controllers\StationsController::index