- path: 
  - /stations/import
  controller: Controllers\StationsController::insert

- path: 
  - /stations/(\d+)
  controller: Controllers\StationsController::address

- path: 
  - /search
  controller: Controllers\StationsController::search

- path: 
  - /allStations
  controller: Controllers\StationsController::allStations

- path: 
  - /nearStation
  controller: Controllers\StationsController::nearStation

- path:
  - 
  controller: Controllers\StationsController::index